version: '2'
services:
  front_angular2:
    restart: 'no'
    build: ./angular2
    volumes:
      - /app/sleepdiary.io/dist_prod
    volumes_from:
      - back_python_accounts_calendar
    ports:
      - "80:80"
    environment:
      FOLDER: 'dist'
    links:
      - back_python_accounts_calendar:back_python_accounts_calendar

  back_python_accounts_calendar:
    restart: 'no'
    build: ./python
    expose:
      - "8000"
    links:
      - db_postgres:db_postgres
    env_file: .env
    environment:
      DEBUG: 'true'
    command: /usr/local/bin/gunicorn sleepdiary_backend.wsgi:application --bind 0.0.0.0:8000 --workers 3

  db_postgres:
    restart: 'no'
    build: ./postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
