version: '2'
services:
  front_angular2:
    restart: 'always'
     build:
        context: ./angular2
        dockerfile: Dockerfile.prod
    volumes:
      - /app/sleepdiary.io/dist_prod
    volumes_from:
      - back_python_accounts_calendar
    ports:
      - "80:80"
    environment:
      FOLDER: 'dist_prod'
    links:
      - back_python_accounts_calendar:back_python_accounts_calendar

  back_python_accounts_calendar:
    restart: 'always'
    build: ./python
    expose:
      - "8000"
    links:
      - db_postgres:db_postgres
    env_file: .prod.env
    environment:
      DEBUG: 'true'
    command: /usr/local/bin/gunicorn sleepdiary_backend.wsgi:application --bind 0.0.0.0:8000 --workers 3

  db_postgres:
    restart: 'always'
    build: ./postgres
    env_file:
      - .prod.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
